### ISSUE TITLE
error when installing (Xcode) on tvOS v. 13.4 for Apple TV 4K 

### ISSUE THREAD

**Issue by MaxoBotanic** [LisaGuide/Apple-TV-tvOS-Safari#1]
<a href="https://ibb.co/ysRT9KK"><img src="https://i.ibb.co/BsPDpvv/2020-05-29-16-40-42.png" alt="2020-05-29-16-40-42" border="0"></a>

Anyone can help me to get the browser on my Apple TV?

**Comment by LisaGuide** [comment]
Hello,

Try cleaning your Xcode project:

⌘ (Command) + ⌥ (Option) + ⇧ (Shift) + K



Also, under build target > Select Generic tvOS device > Then build the project again to see if it compiles. If it works then attempt to build for your Apple TV again. Also verify that your Apple developer credentials are valid and set correctly under project settings.

**Comment by MaxoBotanic** [comment]
Thank you for your help, but it didn't help ) It works in emulation.

<a href="https://ibb.co/GVWBzZQ"><img src="https://i.ibb.co/7Gn8s3t/2020-05-29-17-05-55.png" alt="2020-05-29-17-05-55" border="0"></a>

<a href="https://ibb.co/SvkpcKs"><img src="https://i.ibb.co/mzn70HD/2020-05-29-17-06-50.png" alt="2020-05-29-17-06-50" border="0"></a>

<a href="https://ibb.co/5RP7GSS"><img src="https://i.ibb.co/71q9jZZ/2020-05-29-17-08-32.png" alt="2020-05-29-17-08-32" border="0"></a>

**Comment by MaxoBotanic** [comment]
<a href="https://ibb.co/dj2g8RQ"><img src="https://i.ibb.co/VJSmfsv/2020-05-29-17-17-18.png" alt="2020-05-29-17-17-18" border="0"></a>

<a href="https://ibb.co/BzHxLF6"><img src="https://i.ibb.co/xCK0hdg/2020-05-29-17-17-23.png" alt="2020-05-29-17-17-23" border="0"></a>

**Comment by MaxoBotanic** [comment]
<a href="https://ibb.co/rt7wzPF"><img src="https://i.ibb.co/fS1xyRq/2020-05-29-17-21-33.png" alt="2020-05-29-17-21-33" border="0"></a>

**Comment by LisaGuide** [comment]
Hello,

I just tried it on my Macintosh with the latest version of Xcode and I did not have any problems. Is your Apple TV running tvOS 13.4.5? Is your Xcode fully up-to-date?

You may need to delete the cached files relating to this project

https://stackoverflow.com/questions/22349557/could-not-build-module-uikit-in-cocoapods-since-xcode-5-1

**Comment by MaxoBotanic** [comment]
<a href="https://ibb.co/K6qsrv6"><img src="https://i.ibb.co/dB2p5YB/2020-05-29-17-24-51.png" alt="2020-05-29-17-24-51" border="0"></a>

**Comment by MaxoBotanic** [comment]
Before your program tried to install tor browser (https://github.com/jvanakker/tvOSBrowser). There were also errors like here https://github.com/jvanakker/tvOSBrowser/issues/36. Maybe the problem is that previous files from another project (tvOSBrowser) are affected?

**Comment by LisaGuide** [comment]
It is very possible that something has carried over from a previous build. You may need to fully erase all derived and cached data for Xcode. You may need to fully uninstall then re-install Xcode.

**Comment by MaxoBotanic** [comment]
OK, now I will completely delete Xcode and reinstall it.

**Comment by MaxoBotanic** [comment]
Thank you reinstalling Xcode helped. And you didn't even need to change the file "Availability.h’" as here https://techwiser.com/web-browser-on-apple-tv-4/.

Another thing is that this function "Press the touch area while in cursor mode to click" does not work everywhere. For example, most videos can't play.
